language: python
python:
  - "3.8"
  - "2.7"
install: 
  - pip install -r requirements.txt
  - pip install coveralls
script: 
  - py.test -v -r f --cov=.  --cov-report=html
after_success:
  - coveralls
